### ISSUE TITLE
View on github URLs are wrong

### ISSUE THREAD

**Issue by constantinius** [EOEPCA/open-science-catalog-frontend#362]
When trying to click the "view file on github" button on any catalog item, the user is redirected to a `404` page of the github repository. The issue is that there is a `data/` prefix in the button URL, which should be removed.

**Comment by silvester-pari** [comment]
Thanks, this was actually a misconfiguration on the live deployment env variables, should be fixed with https://github.com/EOEPCA/open-science-catalog-deploy/commit/4fb0e2fa4ffab625de3de6b1afea449991e2188a
