### ISSUE TITLE
Modularize page layout

### ISSUE THREAD

**Issue by silvester-pari** [EOEPCA/open-science-catalog-frontend#69]
Currently, we have similar but slightly different layouts for theme/projects, theme/variables, projects and variables pages. Since they all have a header and an item grid underneath it would be good to always reuse the same layout component.

Also consider re-using the top (header/hero) part in this layout.

**Comment by radupasparuga** [comment]
Standardized Variable + Project pages in https://github.com/EOEPCA/open-science-catalog-frontend/commit/8f6e3ca28cb4df05eb5176d47e80828d269af269
