### ISSUE TITLE
Hide "empty" projects by default in ItemGrid

### ISSUE THREAD

**Issue by silvester-pari** [EOEPCA/open-science-catalog-frontend#72]
Similar to metrics view, projects with 0 products should be hidden by default in the ItemGrid / Search results.

But, there should be a checkbox or something similar to allow the user to display empty projects, maybe this can be a global checkbox with the state stored and also accessible in the metrics view.

**Comment by radupasparuga** [comment]
Handled for variables, waiting for backend and then we can do the same for projects
